### ISSUE TITLE
Assessment Results

### ISSUE THREAD

**Issue by mschae16** [stevecalla/mod_0_skills#1]
@stevecalla - Great work on this assessment, Steve. You are officially `technical ready`! It's clear that you have a solid grasp of OOP principles and variable assignment from Mod 0 lessons. Here's some feedback to keep in mind moving forward:

- Nice work following proper naming conventions (with class names `PascalCase` and attributes/methods `camelCase`)
- Also great to see you using action verbs for your method names!
- Be careful on the `datetime` data type. Technically that's just a string, so I expected to see `purchaseDate: "2020-10-01"` and `hireDate: "2020-01-01"` with the dates wrapped in quotations.
- Good to see your methods modifying your class attributes in some way!

Keep up the great work and let me know if you have any questions!

**Comment by stevecalla** [comment]
@mschae16 Terrific! I will review in detail to be sure I fully grasp your feedback! Thanks again for your efforts. Steve

**Comment by stevecalla** [comment]
@mschae16 I understand regarding dates which are always a challenge (based on my experience in SQL and otherwise. I look forward to learning about functions or other techniques to manage dates. Thanks so much, Steve
